config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"

  namespace :admin do
    resources :users
  end
end

app/models/amazon/asin.rb
module Amazon
    class Asin
        # Return the ASIN from a URL copied and pasted by the user
        # Return false if no ASIN is found
        def self.from_url(amazon_url)
            if amazon_url.match(/\/dp\/(\w{10})(\/|\Z)/)
                # /dp/B0015T963C
                asin = $1
            elsif amazon_url.match(/\/dp\/(\w{10})/)
                # /dp/B0015T963C?
                asin = $1
            elsif amazon_url.match(/\/gp\/\w*?\/(\w{10})(\/|\Z)/)
                # /gp/product/D0015T963C
                asin = $1
            elsif amazon_url.match(/\/gp\/\w*?\/\w*?\/(\w{10})(\/|\Z)/)
                # /gp/product/glance/E0015T963C
                asin = $1
            elsif amazon_url.match(/\/gp\/[\w-]*?\/(\w{10})(\/|\Z)/)
                # /gp/offer-listing/F018Y23P7K
                asin = $1
            elsif amazon_url.match(/\/product-reviews\/(\w{10})(\/|\Z)/)
                # /product-reviews/G018Y23P7K
                asin = $1
            elsif amazon_url.match(/[?&]asin=(\w{10})(&|#|\Z)/i)
                # ?asin=H018Y23P7K
                # &ASIN=H018Y23P7K
                asin = $1
            else
                asin = nil
            end
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    before_validation :set_asin
    monetize :price_cents

    validates_presence_of :name
    validates :url, url: { no_local: true }

    private 
    def set_asin
        self.asin = Amazon::Asin.from_url(url)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i, message: "is not a valid email" }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
    before_action :set_user, only: %i[ show edit update destroy ]

  # GET /admin/users or /admin/users.json
  def index
    @users = User.all
  end

  # GET /admin/users/1 or /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users or /admin/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1 or /admin/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1 or /admin/users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!

  private

  def require_admin!
    unless current_user.try(:admin)
      redirect_to root_path, flash: { error: "Insufficient rights!" }
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :model, :url, :manufacturer, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], class: "bg-white p-10 rounded-lg shadow-lg min-w-full") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :email, class: "text-gray-800 font-semibold block my-3 text-md" %>
    <%= form.email_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :password, class: "text-gray-800 font-semibold block my-3 text-md" %>
    <%= form.password_field :password, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :admin %>
    <%= form.check_box :admin, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="mx-auto text-center">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= user.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Admin:</strong>
    <%= user.admin %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">ID:</strong>
    <%= user.id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user", [:admin, user], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this user', edit_admin_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-center">Editing user</h1>
  <%= render "form", user: @user %>
  <div class="mx-auto text-center m-10">
  <%= link_to "Show this user", [:admin, @user], class: "ml-2 rounded-lg content-center py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', admin_user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-100 font-medium" %>
    </div>
  <%= link_to "Back to users", admin_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_admin_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">#</th>
                <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Email</th>
                <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Admin</th>

                <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                  <tr class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">1</td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= user.email %></td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= user.admin %></td>
                <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= link_to(edit_admin_user_path(user)) do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                </svg>
                <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-center">New user</h1>

  <%= render "form", user: @user %>
  <div class="mx-auto text-center m-10">
    <%= link_to 'Back to users', admin_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_admin_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to admin_user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-100 font-medium inline-block" do %>
        Destroy user <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      <% end.html_safe %>
    </div>
    <%= link_to 'Back to users', admin_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestPrices</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "bg-white p-10 rounded-lg shadow-lg min-w-full") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "text-gray-800 font-semibold block my-3 text-md" %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url, class: "text-gray-800 font-semibold block my-3 text-md" %>
    <%= form.url_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :model %>
    <%= form.text_field :model, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :asin %>
    <%= form.text_field :asin, disabled: true, class: "block shadow rounded-md dark:focus:border-blue-500 cursor-not-allowed border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="mx-auto text-center">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Model:</strong>
    <%= product.model %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Manufacturer:</strong>
    <%= product.manufacturer %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= product.price %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Asin:</strong>
    <%= product.asin %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this product", product, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this product', edit_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-center">Editing product</h1>
  <%= render "form", product: @product %>
  <div class="mx-auto text-center m-10">
  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg content-center py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
      <%= button_to 'Destroy this product', product_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-100 font-medium" %>
    </div>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to 'New product', new_product_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="bg-white border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">#</th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Name</th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Model</th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Manufacturer</th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">price</th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">ASIN</th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Actions</th>
            </tr>
          </thead>
          <tbody>            
            <% @products.each do |product| %>
                <tr class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">1</td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= link_to(product.name, product)%></td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= product.model %></td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= product.manufacturer %></td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= product.price %></td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"><%= product.asin %></td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
              <%= link_to(edit_product_path(product)) do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
              </svg>              
              <% end %>
              </td>
            </tr>
            <% end %>            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-center">New product</h1>

  <%= render "form", product: @product %>
<div class="mx-auto text-center m-10">
  <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
</div>

app/views/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <%= link_to 'Edit this product', edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to product_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-100 font-medium inline-block" do %>
        Destroy product <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      <% end.html_safe %>
    </div>
    <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>